openapi: 3.0.0
info:
  title: AddNotes API
  version: 'v1'
servers:
  - url: https://dev.api.communityfibre.co.uk/dev/work-item/v1
         
  
paths:
  /0.0/add-note:
     description: To add notes to customer interactions 
     post:
      description: To add notes to customer interactions 
      tags:
      - AddNotes
      security:
        - bearerAuth: []
            
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - assignedGroupId
                - createdBy
                - interactionRemarks
                - itemCatgId
                - itemId
                - itemTypeId
                - username
              properties:
                assignedGroupId: 
                  type: string
                  example: 'Complaints'
                createdBy:
                  type: string
                  example: 'CFLHOBS'
                interactionRemarks:
                  type: string
                  example: 'adding notes'
                itemCatgId:
                  type: string
                  example: 'Internal'
                itemId:
                  type: string
                  example: 'C-1320661549'
                itemTypeId:
                  type: string
                  example: 'Notes on Network Issue'
                username:
                  type: string
                  example: 'CFLHOBS'
            example:
              assignedGroupId: 'Complaints'
              createdBy: 'CFLHOBS'
              interactionRemarks: 'adding notes'
              itemCatgId: 'Internal'
              itemId: 'C-1320661549'
              itemTypeId: 'Notes on Network Issue'
              username: 'CFLHOBS'

              
      responses:
        200:
          description: Notes Added Successfully/Failed
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/notesSuccess'
                  - $ref: '#/components/schemas/notesFail'
              examples:
                notesSuccess:
                  value:
                    statusList:
                      - statusCode: '0000'
                        statusDescription: 'Notes Successfully added'
                        statusType: 'Informational'
 
                notesFail:
                  value:
                    statusList:
                      - statusCode: 'UN_0002'
                        statusDescription: 'Item id not available'
                        statusType: 'Warn'
                  
                  
        400:                        
          description: MALFORMED_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                  code:
                    type: string
                    example: "MALFORMED_REQUEST"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Problem parsing request parameters - missing mandatory parameter(s)"
              example:
                uuid: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                code: "MALFORMED_REQUEST"
                messages:
                    - "Problem parsing request parameters - missing mandatory parameter(s)"


        401:  
          description: NOT_AUTHORISED
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                  code:
                    type: string
                    example: "NOT_AUTHORISED"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Not authorised to use this endpoint"
              example:
                uuid: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                code: "NOT_AUTHORISED"
                messages:
                    - "Not authorised to use this endpoint"


        500:  
          description: SUPPLIER_FAULT
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                  code:
                    type: string
                    example: "SUPPLIER_FAULT"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "An unexpected system error occurred"
              example:
                uuid: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                code: "SUPPLIER_FAULT"
                messages:
                    - "An unexpected system error occurred"     
         
components:
  securitySchemes:
    bearerAuth:
      description: |
        The Apigee Gateway can support a number of different authentication mechanisms e.g. JWT bearer tokens
      type: http
      scheme: bearer
      bearerFormat: JWT     
      
  schemas:
      notesSuccess:
        type: object
        properties: 
          statusList:
            type: array
            items:
              type: object
              properties:
                statusCode: 
                  type: string
                  example: '0000'
                statusDescription: 
                  type: string
                  example: 'Notes Successfully added'
                statusType:
                  type: string
                  example: 'Informational'
      notesFail:
        properties: 
          statusList:
            type: array
            items:
              type: object
              properties:
                statusCode: 
                  type: string
                  example: 'UN_0002'
                statusDescription: 
                  type: string
                  example: 'Item id not available'
                statusType:
                  type: string
                  example: 'Warn'
