openapi: 3.0.0
info:
  title: AutoCompensation API
  version: 'v1'
servers:
  - url: https://dev.api.communityfibre.co.uk/dev/supernova/v1
  
paths:
  /0.0/auto-comp:
    post:
      tags:
        - Auto Compensation
      security:
        - bearerAuth: []

      requestBody:
        required: true
        content:
            application/json:
              schema:
                type: object
                required:
                - sentAt
                - eventType
                - compensationEligible
                - identifier
                - appointment
                properties:
                  sentAt:
                    type: string
                    example: "2025-01-29T09:49:39+0000"
                  eventType:
                    type: string
                    enum:
                    - "Missed Appointment"
                    - "Delayed Provisioning"
                    - "Delayed Fault Repair"
                    - "Repair Missed Appointment"
                    example: "Delayed Fault Repair"
                  compensationEligible:
                    type: string
                    example: "Yes"
                  identifier:
                    type: object
                    required:
                    - orderReference
                    - serviceRefId
                    properties:
                      orderReference:
                        type: string
                        example: "ORD-XYZ0001"
                      faultReference:
                        type: string
                        example: "FLT-XYZ0001"
                      serviceRefId:
                        type: string
                        example: "AC-12345"
                      buyerActionID:
                        type: string
                        example: "VFA***"
                  appointment:
                    type: object
                    required:
                      - appointmentDate 
                      - appointmentStartTime
                      - appointmentEndTime
                      - supplierMissedAppointment 
                      - customerMissedAppointment 
                    properties:
                      appointmentReference:
                        type: string
                        example: "REFXYZ0001"
                      appointmentDate:
                        type: string
                        example: "2024-12-01"
                      appointmentStartTime:
                        type: string
                        example: "0800"
                      appointmentEndTime:
                        type: string
                        example: "1200"
                      supplierMissedAppointment:
                        type: string
                        example: "Yes"
                      customerMissedAppointment:
                        type: string
                        example: "No"
                      appointmentAmended:
                        type: string
                        example: "Yes"
                      appointmentCancelled:
                        type: string
                        example: ""
                      endCustomerAgreed:
                        type: string
                        example: ""
                  delayDays:
                    type: object
                    properties:
                      totalDelayDays:
                        type: integer
                        example: 10
                      supplierDelayDays:
                        type: integer
                        example: 8
                      nonSupplierDelayDays:
                        type: integer
                        example: 1
                  exclusion:
                    type: object
                    properties:
                      exclusionReason:
                        type: string
                        example: "RF3CF"
                      numberOfDays:
                        type: integer
                        example: 1
                      exclusionStartDate:
                        type: string
                        example: "2024-12-29"
                      exclusionEndDate:
                        type: string
                        example: "2024-12-30"
              examples:
                ProvisioningCustomerReason:
                  value:
                    sentAt: '2025-01-29T09:49:39+0000'
                    eventType: 'Missed Appointment'
                    compensationEligible: 'Yes'
                    identifier:
                      orderReference: 'ORD-XYZ0001'
                      serviceRefId: 'AC-12345'
                    appointment:
                      appointmentReference: 'REFXYZ0001'
                      appointmentDate: '2024-12-01'
                      appointmentStartTime: '0800'
                      appointmentEndTime: '1200'
                      supplierMissedAppointment: 'Yes'
                      customerMissedAppointment: 'No'
                      appointmentAmended: 'Yes'
                      appointmentCancelled: ''
                      endCustomerAgreed: ''
                ProvisioningSupplierReason:
                  value:
                    sentAt: '2025-01-29T09:49:39+0000'
                    event: 'Delayed Provisioning'
                    eventType: 'Delayed Provisioning'
                    compensationEligible: 'Yes'
                    identifier:
                      orderReference: 'ORD-XYZ0001'
                      serviceRefId: 'AC-12345'
                    delayDays:
                      totalDelayDays: 10
                      supplierDelayDays: 8
                      nonSupplierDelayDays: 1
                    exclusion:
                      exclusionReason: 'RF3CF'
                      numberOfDays: 1
                      exclusionStartDate: '2024-12-29'
                      exclusionEndDate: '2024-12-30'
                RepairCustomerReason:
                  value:
                    sentAt: '2025-01-29T09:49:39+0000'
                    eventType: 'Missed Appointment'
                    compensationEligible: 'Yes'
                    identifier:
                      Fault reference: 'FLT-XYZ0001'
                      Service Ref ID: 'AC-12345'
                      BuyerActionID: 'VFA***'
                    appointment:
                      appointmentReference: 'REFXYZ0001'
                      appointmentDate: '2024-12-01'
                      appointmentStartTime: '0800'
                      appointmentEndTime: '1200'
                      supplierMissedAppointment: 'No'
                      customerMissedAppointment: 'Yes'
                      appointmentAmended: ''
                      appointmentCancelled: ''
                      endCustomerAgreed: ''
                RepairSupplierReason:
                  value:
                    sentAt: '2025-01-29T09:49:39+0000'
                    eventType: 'Delayed Fault Repair'
                    compensationEligible: 'Yes'
                    identifier:
                      Fault reference: 'FLT-XYZ0001'
                      Service Ref ID: 'AC-12345'
                      BuyerActionID: 'VFA***'
                    delayDays:
                      totalDelayDays: 10
                      supplierDelayDays: 8
                      nonSupplierDelayDays: 1
                    appointment:
                      appointmentReference: 'REFXYZ0001'
                      appointmentDate: '2024-12-01'
                      appointmentStartTime: '0800'
                      appointmentEndTime: '1200'
                      supplierMissedAppointment: 'Yes'
                      customerMissedAppointment: 'No'
                      appointmentAmended: 'Yes'
                      appointmentCancelled: ''
                      endCustomerAgreed: ''
                    exclusion:
                      exclusionReason: 'RF3CF'
                      numberOfDays: 1
                      exclusionStartDate: '2024-12-29'
                      exclusionEndDate: '2024-12-30'
    

      responses:
        '200':
          description: Success
          
          
        '400':                        
          description: MALFORMED_REQUEST
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                  code:
                    type: string
                    example: "MALFORMED_REQUEST"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Problem parsing request parameters - missing mandatory parameter(s)"
              example:
                uuid: "2b7e6837-0ec3-4ee9-acba-8250768c5ef9"
                code: "MALFORMED_REQUEST"
                messages:
                    - "Problem parsing request parameters - missing mandatory parameter(s)"


        '401':  
          description: NOT_AUTHORISED
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                  code:
                    type: string
                    example: "NOT_AUTHORISED"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "Not authorised to use this endpoint"
              example:
                uuid: "1e7e7ebc-c797-4d60-a81c-940b40631957"
                code: "NOT_AUTHORISED"
                messages:
                    - "Not authorised to use this endpoint"


        '500':  
          description: SUPPLIER_FAULT
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    example: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                  code:
                    type: string
                    example: "SUPPLIER_FAULT"
                  messages:
                    type: array
                    items:
                      type: string
                      example: "An unexpected system error occurred"
              example:
                uuid: "43c871f3-18f4-46f8-9674-26ccd1dcee14"
                code: "SUPPLIER_FAULT"
                messages:
                    - "An unexpected system error occurred"


components:
  securitySchemes:
    bearerAuth:
      description: |
        The Apigee Gateway can support a number of different authentication mechanisms e.g. JWT bearer tokens
      type: http
      scheme: bearer
      bearerFormat: JWT